###Installing dependecies based on the documentation provided over at the website.

In [0]:
!pip install numpy

In [0]:
!pip install pandas

In [0]:
!pip install netcdf4

In [0]:
!python3 -m pip install --upgrade pandas

Requirement already up-to-date: pandas in /Users/saviosebastian/anaconda3/lib/python3.6/site-packages (0.23.4)


In [0]:
!python -m pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose

###Installing the XArray package

In [0]:
!pip install xarray

In [0]:
!pip install -U pytest

    100% |████████████████████████████████| 215kB 5.0MB/s ta 0:00:01
  Found existing installation: pluggy 0.6.0
    Uninstalling pluggy-0.6.0:
      Successfully uninstalled pluggy-0.6.0
  Found existing installation: pytest 3.5.1
    Uninstalling pytest-3.5.1:
      Successfully uninstalled pytest-3.5.1


In [0]:
!pip install mock

    100% |████████████████████████████████| 61kB 1.8MB/s ta 0:00:01
    100% |████████████████████████████████| 102kB 5.5MB/s a 0:00:011


In [0]:
!py.test --pyargs xarray

============================= test session starts ==============================
platform darwin -- Python 3.6.5, pytest-3.8.0, py-1.5.3, pluggy-0.7.1
rootdir: /Users/saviosebastian/Desktop/XArraysTest, inifile:
plugins: remotedata-0.2.1, openfiles-0.3.0, doctestplus-0.1.3, arraydiff-0.2
collected 6858 items / 1 skipped                                               

xarray/tests/test_accessors.py ......................................... [  0%]
..............................................................           [  1%]
xarray/tests/test_backends.py .......................................... [  2%]
........................................................................ [  3%]
........................................................................ [  4%]
........................................................................ [  5%]
.................sssssssssssssssssssssssssssssssssssssssssssssssssssssss [  6%]
sssssssssssssssssssssssssssssssssssssssssssssssssssssssssss...........

                # Need to force instantiation so we can reliably
                # tell if we get the same exception back
                value = type()
            try:
>               self.gen.throw(type, value, traceback)

../../anaconda3/lib/python3.6/contextlib.py:99: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

suffix = '.nc', allow_cleanup_failure = False

    @contextlib.contextmanager
    def create_tmp_file(suffix='.nc', allow_cleanup_failure=False):
        temp_dir = tempfile.mkdtemp()
        path = os.path.join(temp_dir, 'temp-%s%s' % (next(_counter), suffix))
        try:
            yield path
        finally:
            try:
>               shutil.rmtree(temp_dir)

../../anaconda3/lib/python3.6/site-packages/xarray/tests/test_backends.py:888: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

path = '/var/folders/wd/6mcc6nzd4qx7cd_y1brbrsqc0000gn/T/tmpba4bb8li'
ignore_errors = False
onerror = <funct


    def _exit_wrapper(*exc_details):
>       return cm_exit(cm, *exc_details)

../../anaconda3/lib/python3.6/contextlib.py:284: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <contextlib._GeneratorContextManager object at 0x1c14464240>
type = <class 'OSError'>, value = OSError(24, 'Too many open files')
traceback = <traceback object at 0x1c2e1cb2c8>

    def __exit__(self, type, value, traceback):
        if type is None:
            try:
                next(self.gen)
            except StopIteration:
                return False
            else:
                raise RuntimeError("generator didn't stop")
        else:
            if value is None:
                # Need to force instantiation so we can reliably
                # tell if we get the same exception back
                value = type()
            try:
>               self.gen.throw(type, value, traceback)

../../anaconda3/lib/python3.6/contextlib.py:99: 
_ _ _ _ _ _ _ _ _ _ _ 

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <contextlib._GeneratorContextManager object at 0x1c148bc710>
type = <class 'OSError'>, value = OSError(24, 'Too many open files')
traceback = <traceback object at 0x1c16935108>

    def __exit__(self, type, value, traceback):
        if type is None:
            try:
                next(self.gen)
            except StopIteration:
                return False
            else:
                raise RuntimeError("generator didn't stop")
        else:
            if value is None:
                # Need to force instantiation so we can reliably
                # tell if we get the same exception back
                value = type()
            try:
>               self.gen.throw(type, value, traceback)

../../anaconda3/lib/python3.6/contextlib.py:99: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

suffix = '.nc', allow_cleanup_failure = False

    @contextlib.context

../../anaconda3/lib/python3.6/contextlib.py:99: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

suffix = '.nc', allow_cleanup_failure = False

    @contextlib.contextmanager
    def create_tmp_file(suffix='.nc', allow_cleanup_failure=False):
        temp_dir = tempfile.mkdtemp()
        path = os.path.join(temp_dir, 'temp-%s%s' % (next(_counter), suffix))
        try:
            yield path
        finally:
            try:
>               shutil.rmtree(temp_dir)

../../anaconda3/lib/python3.6/site-packages/xarray/tests/test_backends.py:888: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

path = '/var/folders/wd/6mcc6nzd4qx7cd_y1brbrsqc0000gn/T/tmpdqwts4dd'
ignore_errors = False
onerror = <function rmtree.<locals>.onerror at 0x1c14228158>

    def rmtree(path, ignore_errors=False, onerror=None):
        """Recursively delete a directory tree.
    
        If ignore_errors is set, errors are ignored; otherwise, if one

/Users/saviosebastian/anaconda3/lib/python3.6/site-packages/scipy/io/netcdf.py:317: RuntimeWarning: Cannot close a netcdf_file opened with mmap=True, when netcdf_variables or arrays referring to its data still exist. All data arrays obtained from such files refer directly to data on disk, and must be copied before the file can be cleanly closed. (See netcdf_file docstring for more information on mmap.)
  ), category=RuntimeWarning)
/Users/saviosebastian/anaconda3/lib/python3.6/site-packages/scipy/io/netcdf.py:317: RuntimeWarning: Cannot close a netcdf_file opened with mmap=True, when netcdf_variables or arrays referring to its data still exist. All data arrays obtained from such files refer directly to data on disk, and must be copied before the file can be cleanly closed. (See netcdf_file docstring for more information on mmap.)
  ), category=RuntimeWarning)
/Users/saviosebastian/anaconda3/lib/python3.6/site-packages/scipy/io/netcdf.py:317: RuntimeWarning: Cannot close a netcdf_file o

###Importing dependencies for the program.

In [0]:
import pandas as pd

In [0]:
import numpy as np

###Creating a random numpy array of (4,3)

In [0]:
data = np.random.rand(4,3)

In [0]:
locs = {'IA','IL','IN'}

In [0]:
times = pd.date_range('2000-01-01',periods=4)

In [0]:
import xarray as xr

###Creating a DataArray of the numpy array.

In [0]:
foo = xr.DataArray(data)

###Describing & Evaluating the 'foo' and its attributes

In [0]:
foo

<xarray.DataArray (dim_0: 4, dim_1: 3)>
array([[0.159038, 0.524521, 0.362766],
       [0.271877, 0.955653, 0.153606],
       [0.073735, 0.889903, 0.289227],
       [0.21128 , 0.33466 , 0.53737 ]])
Dimensions without coordinates: dim_0, dim_1

In [0]:
foo.values

array([[0.15903754, 0.52452053, 0.36276556],
       [0.27187684, 0.95565284, 0.15360555],
       [0.07373492, 0.88990319, 0.28922653],
       [0.21127977, 0.33466035, 0.53737023]])

In [0]:
foo.dims

('dim_0', 'dim_1')

In [0]:
foo.coords

Coordinates:
    *empty*

In [0]:
foo.attrs

OrderedDict()

In [0]:
foo.name='foo'

In [0]:
import xarray as xr

In [0]:
foo = xr.DataArray('MYD03.A2002185.0000.061.2017362174430.hdf')

In [0]:
foo

<xarray.DataArray ()>
array('MYD03.A2002185.0000.061.2017362174430.hdf', dtype='<U41')

In [0]:
foo.dims

()

In [0]:
foo.values

array('MYD03.A2002185.0000.061.2017362174430.hdf', dtype='<U41')

###Attempting to open the HDF dataset

In [0]:
fio = xr.open_dataset('MYD03.A2002185.0000.061.2017362174430.hdf')

MissingDimensionsError: 'Scan Type' has more than 1-dimension and the same name as one of its dimensions ('nscans', 'Scan Type'). xarray disallows such variables because they conflict with the coordinates used to label dimensions.

###Issue : There doesnt seem to be a direct support for HDF files with the Dataset function.
###Feedback: 

In [0]:
gem=xr.Dataset('MYD03.A2002185.0000.061.2017362174430.hdf')

AttributeError: 'str' object has no attribute 'items'

In [0]:
tim = xr.save_mfdataset('/Users/saviosebastian/Desktop/XArraysTest/MYD03.A2002185.0000.061.2017362174430.hdf',paths)

NameError: name 'paths' is not defined

In [0]:
paths = ['%s.nc']

###Attempting to read the Dataset through netCDF package 

In [0]:
#!/usr/bin/env python

from netCDF4 import Dataset
import sys

num_args = len(sys.argv)
if (num_args < 3) : 
	print ("Insufficient arguments")
	exit()

mod03_name = 'MYD03.A2002185.0000.061.2017362174430.hdf'
mod06_name = 'MYD06_L2.A2002185.0000.061.2018003215042.hdf'

print(mod03_name)
print(mod06_name)

rootgrp = Dataset(mod03_name, "r", format="NETCDF3")
latitude = rootgrp.variables["Latitude"][:,:] 
longitude = rootgrp.variables["Longitude"][:,:]
print("------------------------------------")
print (longitude)
print("------------------------------------")
print (longitude.size)
print("------------------------------------")
data_ht = latitude.shape[0]
data_wid = longitude.shape[1]
print (data_wid)
print (data_ht)

print (rootgrp.variables.keys())

#for name, variable in rootgrp.variables.items():
#	print("=== VARNAME: ", name, " =======")
#	for attrname in variable.ncattrs():
#		print("{} -- {}".format(attrname, getattr(variable, attrname)))


rootgrp.close()

rootgrp = Dataset(mod06_name, "r", format="NETCDF3")
cloud_mask_allbytes = rootgrp.variables["Cloud_Mask_1km"][:,:,:] 
print(cloud_mask_allbytes.shape)
print("------------------------------------")
print (rootgrp.variables.keys())
rootgrp.close()




MYD03.A2002185.0000.061.2017362174430.hdf
MYD06_L2.A2002185.0000.061.2018003215042.hdf
------------------------------------
[[-- -- -- ... -- -- --]
 [-- -- -- ... -- -- --]
 [-- -- -- ... -- -- --]
 ...
 [15.015028953552246 15.064740180969238 15.11345100402832 ...
  38.32621383666992 38.37139129638672 38.41727066040039]
 [15.014087677001953 15.063920021057129 15.112410545349121 ...
  38.32081985473633 38.366085052490234 38.41202926635742]
 [15.01251220703125 15.062713623046875 15.111570358276367 ...
  38.31563949584961 38.36115646362305 38.4079704284668]]
------------------------------------
2762160
------------------------------------
1354
2040
odict_keys(['Latitude', 'Longitude', 'Scan Offset', 'Track Offset', 'Height Offset', 'Height', 'SensorZenith', 'SensorAzimuth', 'Range', 'SolarZenith', 'SolarAzimuth', 'Land/SeaMask', 'WaterPresent', 'gflags', 'Scan number', 'EV frames', 'SD frames', 'SV frames', 'EV start time', 'SD start time', 'SV start time', 'EV center time', 'Mirror side

In [0]:
import xarray as xr
ds = xr.open_dataset('MYD03.A2002185.0000.061.2017362174430.hdf',engine='netCDF4')

ValueError: unrecognized engine for open_dataset: 'netCDF4'

In [0]:
ds_disk = xr.open_dataset('MYD03.A2002185.0000.061.2017362174430.hdf')

MissingDimensionsError: 'Scan Type' has more than 1-dimension and the same name as one of its dimensions ('nscans', 'Scan Type'). xarray disallows such variables because they conflict with the coordinates used to label dimensions.

In [0]:
ls

###Attempting to read a default NetCDF4 NC file.

In [0]:
ds_disk = xr.open_dataset('sresa1b_ncar_ccsm3-example.nc')

In [0]:
ds_disk

<xarray.Dataset>
Dimensions:    (bnds: 2, lat: 128, lon: 256, plev: 17, time: 1)
Coordinates:
  * lat        (lat) float32 -88.927734 -87.538704 ... 87.538704 88.927734
  * lon        (lon) float32 0.0 1.40625 2.8125 ... 355.78125 357.1875 358.59375
  * plev       (plev) float64 1e+05 9.25e+04 8.5e+04 7e+04 ... 3e+03 2e+03 1e+03
  * time       (time) datetime64[ns] 2000-05-16T12:00:00
Dimensions without coordinates: bnds
Data variables:
    area       (lat, lon) float32 ...
    lat_bnds   (lat, bnds) float64 ...
    lon_bnds   (lon, bnds) float64 ...
    msk_rgn    (lat, lon) int32 ...
    pr         (time, lat, lon) float32 ...
    tas        (time, lat, lon) float32 ...
    time_bnds  (time, bnds) float64 ...
    ua         (time, plev, lat, lon) float32 ...
Attributes:
    CVS_Id:              $Id$
    creation_date:       
    prg_ID:              Source file unknown Version unknown Date unknown
    cmd_ln:              bds -x 256 -y 128 -m 23 -o /data/zender/data/dst_T85.nc
    hi

In [0]:
foo = xr.open_dataset('MYD03.A2002185.0000.061.2017362174430.hdf')

MissingDimensionsError: 'Scan Type' has more than 1-dimension and the same name as one of its dimensions ('nscans', 'Scan Type'). xarray disallows such variables because they conflict with the coordinates used to label dimensions.

In [0]:
foo.nbytes / 1e6

0.000164

In [0]:
help(xr.tutorial.load_dataset)

Help on function load_dataset in module xarray.tutorial:

load_dataset(name, cache=True, cache_dir='~/.xarray_tutorial_data', github_url='https://github.com/pydata/xarray-data', branch='master', **kws)
    Load a dataset from the online repository (requires internet).
    
    If a local copy is found then always use that to avoid network traffic.
    
    Parameters
    ----------
    name : str
        Name of the netcdf file containing the dataset
        ie. 'air_temperature'
    cache_dir : string, optional
        The directory in which to search for and write cached data.
    cache : boolean, optional
        If True, then cache data locally for use on subsequent calls
    github_url : string
        Github repository where the data is stored
    branch : string
        The git branch to download from
    kws : dict, optional
        Passed to xarray.open_dataset



In [0]:
ls

MYD03.A2002185.0000.061.2017362174430.hdf
MYD06_L2.A2002185.0000.061.2018003215042.hdf
SamVersionOfSavioCode.ipynb
SamVersionOfSavioCode1.ipynb
XArray-Test.ipynb
sresa1b_ncar_ccsm3-example.nc
test_echam_spectral.nc
test_hgroups.nc


In [0]:
from __future__ import division, print_function
import numpy as np
import matplotlib as mpl
mpl.use('Agg')
from matplotlib import pyplot as plt
from netCDF4 import Dataset
import os,datetime,sys,fnmatch
from jdcal import gcal2jd
#from plot_global_map import *
import math

In [0]:
MOD03_path = '/Users/saviosebastian/Desktop/XArraysTest/'
MOD06_path = '/Users/saviosebastian/Desktop/XArraysTest/'
satellite = 'Aqua'

In [0]:
MOD03_fp = 'MYD03.A*.hdf'
MOD06_fp = 'MYD06_L2.A*.hdf'
MOD03_fn, MOD06_fn =[],[]

In [11]:
#!/usr/bin/env python
from __future__ import division, print_function
import numpy as np
import matplotlib as mpl
mpl.use('Agg')
from matplotlib import pyplot as plt
from netCDF4 import Dataset
import os,datetime,sys,fnmatch
from jdcal import gcal2jd
#from plot_global_map import *
import math

def read_MODIS_level2_data(MOD06_file,MOD03_file):
    print(MOD06_file)
    print(MOD03_file)
    print('reading the cloud mask from MOD06_L2 product')
    MOD06 = Dataset(MOD06_file, 'r')
    print("-----------------------------------------------")
    print(MOD06)
    print("-----------------------------------------------")
    CM1km = MOD06.variables['Cloud_Mask_1km']
    print(CM1km)
    CM   = (np.array(CM1km[:,:,0],dtype='byte') & 0b00000110) >>1
    print('level-2 cloud mask array shape',CM.shape)

    MOD03 = Dataset(MOD03_file,'r')
    print('reading the lat-lon from MOD03 product')
    lat  = MOD03.variables['Latitude']
    print(lat)
    lon  = MOD03.variables['Longitude']
    print('level-2 lat-lon array shape',lat.shape)

    return lat,lon,CM

def value_locate(refx, x):
    refx = np.array(refx)
    x = np.array(x)
    loc = np.zeros(len(x), dtype='int')

    for i in range(len(x)):
        ix = x[i]
        ind = ((refx - ix) <= 0).nonzero()[0]
        if len(ind) == 0:
            loc[i] = -1
        else: loc[i] = ind[-1]

    return loc

def division(n, d):

    div = np.zeros(len(d))
    for i in range(len(d)):
        if d[i] >0:
          div[i]=n[i]/d[i]
        else: div[i]=None 

    return div


# beginning of the program
if __name__ == '__main__':
    import itertools
    MOD03_path = '/Users/saviosebastian/Desktop/XArraysTest/'
    MOD06_path = '/Users/saviosebastian/Desktop/XArraysTest/'
    satellite = 'Aqua'

    yr = [2008]
    mn = [1] #np.arange(1,13)  #[1]
    dy = [1] #np.arange(1,32) # [1] #np.arange(1,31)
    # latitude and longtitude boundaries of level-3 grid
    lat_bnd = np.arange(-90,91,1)
    lon_bnd = np.arange(-180,180,1)
    nlat = 180
    nlon = 360

    TOT_pix      = np.zeros(nlat*nlon)
    CLD_pix      = np.zeros(nlat*nlon)

    #for y,m,d in  itertools.product(yr,mn, dy):
        #-------------find the MODIS prodcts--------------#
    #    date = datetime.datetime(y,m,d)
    #    JD01, JD02 = gcal2jd(y,1,1)
    #    JD1, JD2 = gcal2jd(y,m,d)
    #    JD = np.int((JD2+JD1)-(JD01+JD02) + 1)
    #    granule_time = datetime.datetime(y,m,d,0,0)
    #    while granule_time <= datetime.datetime(y,m,d,23,55):  # 23,55
    #        print('granule time:',granule_time)
    MOD03_fp = 'MYD03.A*.hdf'
    MOD06_fp = 'MYD06_L2.A*.hdf'
    MOD03_fn, MOD06_fn =[],[]
    for MOD06_flist in  os.listdir(MOD06_path):
        if fnmatch.fnmatch(MOD06_flist, MOD06_fp):
           MOD06_fn = MOD06_flist
    for MOD03_flist in  os.listdir(MOD03_path):
        if fnmatch.fnmatch(MOD03_flist, MOD03_fp):
           MOD03_fn = MOD03_flist
    if MOD03_fn and MOD06_fn: # if both MOD06 and MOD03 products are in the directory
                print('reading level 2 geolocation and cloud data')
                print(MOD06_fn)
                Lat,Lon,CM = read_MODIS_level2_data(MOD06_path+MOD06_fn,MOD03_path+MOD03_fn)
                Lat=np.ravel(Lat)
                Lon=np.ravel(Lon)
                CM=np.ravel(CM)
                print('Total Number of pixels in this granule (cloud mask CM>=0)',np.sum(CM>=0))
                print('Total Number of cloudy pixels (cloud mask CM<=1)',np.sum(CM<=1))
                print('cloud fraction of this granule',np.sum(CM<=1)/np.sum(CM>=0))
                print('projecting granule on level3 lat lon grids')
                lat_index = value_locate(lat_bnd,Lat)
                lon_index = value_locate(lon_bnd,Lon)
                latlon_index = lat_index*nlon + lon_index
                print(latlon_index)
                print('computing simple level3 statistics')
                latlon_index_unique = np.unique(latlon_index)
                print('this granule occupies',latlon_index_unique.size,'1x1 degree box')
                for i in np.arange(latlon_index_unique.size):
                    j=latlon_index_unique[i]
                    TOT_pix[j] = TOT_pix[j]+np.sum(CM[np.where(latlon_index == j)]>=0)
                    CLD_pix[j] = CLD_pix[j]+np.sum(CM[np.where(latlon_index == j)]<=1) 
                
                #granule_time += datetime.timedelta(minutes=5)

    print('derive the averaged Level-3 cloud fraction')
    total_cloud_fraction  =  division(CLD_pix,TOT_pix).reshape([nlat,nlon])
    print(np.nansum(total_cloud_fraction))

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-121>", line 2, in initialize
  File "/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
   

ModuleNotFoundError: ignored

In [0]:
MOD06 = Dataset('/Users/saviosebastian/Desktop/XArraysTest/MYD06_L2.A2002185.0000.061.2018003215042.hdf', 'r')
CM1km = MOD06.variables['Cloud_Mask_1km']
print(CM1km)

In [0]:
print(CM1km)

<class 'netCDF4._netCDF4.Variable'>
int8 Cloud_Mask_1km(Cell_Along_Swath_1km:mod06, Cell_Across_Swath_1km:mod06, Cloud_Mask_1km_Num_Bytes:mod06)
    valid_range: [ 0 -1]
    _FillValue: 0
    long_name: MODIS Cloud Mask, L2 MOD06 QA Plan
    units: none
    scale_factor: 1.0
    add_offset: 0.0
    Parameter_Type: MODIS Input
    Cell_Along_Swath_Sampling: [   1 2040    1]
    Cell_Across_Swath_Sampling: [   1 1354    1]
    Geolocation_Pointer: External MODIS geolocation product
    description: See MODIS atmosphere QA plan for details                                            

unlimited dimensions: 
current shape = (2040, 1354, 2)
filling on


In [0]:
print(MOD06.dimensions)

OrderedDict([('Cell_Along_Swath_5km:mod06', <class 'netCDF4._netCDF4.Dimension'>: name = 'Cell_Along_Swath_5km:mod06', size = 408
), ('Cell_Across_Swath_5km:mod06', <class 'netCDF4._netCDF4.Dimension'>: name = 'Cell_Across_Swath_5km:mod06', size = 270
), ('Band_Number:mod06', <class 'netCDF4._netCDF4.Dimension'>: name = 'Band_Number:mod06', size = 7
), ('Band_Forcing:mod06', <class 'netCDF4._netCDF4.Dimension'>: name = 'Band_Forcing:mod06', size = 5
), ('Band_Ratio:mod06', <class 'netCDF4._netCDF4.Dimension'>: name = 'Band_Ratio:mod06', size = 5
), ('Cell_Along_Swath_1km:mod06', <class 'netCDF4._netCDF4.Dimension'>: name = 'Cell_Along_Swath_1km:mod06', size = 2040
), ('Cell_Across_Swath_1km:mod06', <class 'netCDF4._netCDF4.Dimension'>: name = 'Cell_Across_Swath_1km:mod06', size = 1354
), ('Cloud_Mask_5km_Num_Bytes:mod06', <class 'netCDF4._netCDF4.Dimension'>: name = 'Cloud_Mask_5km_Num_Bytes:mod06', size = 2
), ('QA_Parameter_5km:mod06', <class 'netCDF4._netCDF4.Dimension'>: name = 'QA

In [0]:
print(MOD06.file_format)

NETCDF4


In [0]:
print(MOD06.title)

MODIS Level 2 Cloud Properties                                                      



In [0]:
help(xr.Dataframes)

AttributeError: module 'xarray' has no attribute 'Dataframes'

In [0]:
help(xr.Dataset)

Help on class Dataset in module xarray.core.dataset:

class Dataset(collections.abc.Mapping, xarray.core.common.ImplementsDatasetReduce, xarray.core.common.DataWithCoords, xarray.core.formatting.ReprMixin)
 |  A multi-dimensional, in memory, array database.
 |  
 |  A dataset resembles an in-memory representation of a NetCDF file, and
 |  consists of variables, coordinates and attributes which together form a
 |  self describing dataset.
 |  
 |  Dataset implements the mapping interface with keys given by variable names
 |  and values given by DataArray objects for each variable name.
 |  
 |  One dimensional variables with name equal to their dimension are index
 |  coordinates used for label based indexing.
 |  
 |  Method resolution order:
 |      Dataset
 |      collections.abc.Mapping
 |      collections.abc.Collection
 |      collections.abc.Sized
 |      collections.abc.Iterable
 |      collections.abc.Container
 |      xarray.core.common.ImplementsDatasetReduce
 |      xarray.c

In [0]:
foo = xr.Dataset('MOD06')

AttributeError: 'str' object has no attribute 'items'

In [0]:
da = xr.DataArray('/Users/saviosebastian/Desktop/XArraysTest/MYD06_L2.A2002185.0000.061.2018003215042.hdf')

In [0]:
da

<xarray.DataArray ()>
array('/Users/saviosebastian/Desktop/XArraysTest/MYD06_L2.A2002185.0000.061.2018003215042.hdf',
      dtype='<U86')

In [0]:
da.all

<bound method ImplementsArrayReduce._reduce_method.<locals>.wrapped_func of <xarray.DataArray ()>
array('/Users/saviosebastian/Desktop/XArraysTest/MYD06_L2.A2002185.0000.061.2018003215042.hdf',
      dtype='<U86')>

In [0]:
da.data

array('/Users/saviosebastian/Desktop/XArraysTest/MYD06_L2.A2002185.0000.061.2018003215042.hdf',
      dtype='<U86')

In [0]:
da.dtype

dtype('<U86')

In [0]:
da.nbytes / 1e6

0.000344

In [0]:
da.size

1

In [0]:
da.values

array('/Users/saviosebastian/Desktop/XArraysTest/MYD06_L2.A2002185.0000.061.2018003215042.hdf',
      dtype='<U86')

In [0]:
ds = xr.Dataset('/Users/saviosebastian/Desktop/XArraysTest/MYD06_L2.A2002185.0000.061.2018003215042.hdf')

AttributeError: 'str' object has no attribute 'items'

In [0]:
locs = ['IA', 'IL', 'IN']

In [0]:
times = pd.date_range('2000-01-01', periods=4)

In [0]:

print(MOD06)
data = MOD06
print("---------------")
print(data)

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF4):
    HDFEOSVersion: HDFEOS_V2.19
    StructMetadata.0: GROUP=SwathStructure
	GROUP=SWATH_1
		SwathName="mod06"
		GROUP=Dimension
			OBJECT=Dimension_1
				DimensionName="Cell_Across_Swath_5km"
				Size=270
			END_OBJECT=Dimension_1
			OBJECT=Dimension_2
				DimensionName="Cell_Along_Swath_5km"
				Size=408
			END_OBJECT=Dimension_2
			OBJECT=Dimension_3
				DimensionName="Cell_Across_Swath_1km"
				Size=1354
			END_OBJECT=Dimension_3
			OBJECT=Dimension_4
				DimensionName="Cell_Along_Swath_1km"
				Size=2040
			END_OBJECT=Dimension_4
			OBJECT=Dimension_5
				DimensionName="Cell_Across_Swath_hkm"
				Size=2708
			END_OBJECT=Dimension_5
			OBJECT=Dimension_6
				DimensionName="Cell_Along_Swath_hkm"
				Size=4060
			END_OBJECT=Dimension_6
			OBJECT=Dimension_7
				DimensionName="Band_Number"
				Size=7
			END_OBJECT=Dimension_7
			OBJECT=Dimension_8
				DimensionName="Band_Ratio"
				Size=5
			END_OBJEC

In [0]:
foo = xr.DataArray(data)

KeyError: 'name'

In [0]:
cm = data.variables['Cloud_Mask_1km'][:]

In [0]:
MOD03 = Dataset('/Users/saviosebastian/Desktop/XArraysTest/MYD03.A2002185.0000.061.2017362174430.hdf', 'r')

In [6]:
lat = MOD03.variables['Latitude'][:]

NameError: ignored

In [0]:
lat

masked_array(
  data=[[--, --, --, ..., --, --, --],
        [--, --, --, ..., --, --, --],
        [--, --, --, ..., --, --, --],
        ...,
        [30.023902893066406, 30.0213565826416, 30.018844604492188, ...,
         26.660354614257812, 26.649608612060547, 26.63867950439453],
        [30.005863189697266, 30.003368377685547, 30.000919342041016, ...,
         26.643115997314453, 26.632293701171875, 26.621292114257812],
        [29.987855911254883, 29.985397338867188, 29.982986450195312, ...,
         26.62582778930664, 26.614887237548828, 26.603618621826172]],
  mask=[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],
  fill_value=-999.0,
  dtype=float32)

In [0]:
long = MOD03.variables['Longitude'][:]

In [0]:
long

masked_array(
  data=[[--, --, --, ..., --, --, --],
        [--, --, --, ..., --, --, --],
        [--, --, --, ..., --, --, --],
        ...,
        [15.015028953552246, 15.064740180969238, 15.11345100402832, ...,
         38.32621383666992, 38.37139129638672, 38.41727066040039],
        [15.014087677001953, 15.063920021057129, 15.112410545349121, ...,
         38.32081985473633, 38.366085052490234, 38.41202926635742],
        [15.01251220703125, 15.062713623046875, 15.111570358276367, ...,
         38.31563949584961, 38.36115646362305, 38.4079704284668]],
  mask=[[ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        [ True,  True,  True, ...,  True,  True,  True],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]],
  fill_value=-999.0,
  dtype=float32)

In [5]:
Lat=np.ravel(lat)

NameError: ignored

In [2]:
import numpy as np


In [3]:
np

<module 'numpy' from '/Users/saviosebastian/anaconda3/lib/python3.6/site-packages/numpy/__init__.py'>

In [4]:
a = np.arange(1000)

In [5]:
a

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [6]:
b = np.arange(50,50)

In [7]:
b

array([], dtype=int64)

In [8]:
help(np.arange)

Help on built-in function arange in module numpy.core.multiarray:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range <http://docs.python.org/lib/built-in-funcs.html>`_ function,
    but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use ``linspace`` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and

In [13]:
a = np.ones((50, 50))

In [14]:
a

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [15]:
help(np.reshape)

Help on function reshape in module numpy.core.fromnumeric:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the firs

In [16]:
a

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [20]:
b = a.reshape((25,100))

In [21]:
b

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [25]:
q = np.arange(4*3*2)

In [28]:
q.size

24

In [29]:
import xarray as xr

In [30]:
d = xr.to_dataframe(a)

AttributeError: module 'xarray' has no attribute 'to_dataframe'

In [35]:
help(xr.DataArray)

Help on class DataArray in module xarray.core.dataarray:

class DataArray(xarray.core.common.AbstractArray, xarray.core.common.DataWithCoords)
 |  N-dimensional array with labeled coordinates and dimensions.
 |  
 |  DataArray provides a wrapper around numpy ndarrays that uses labeled
 |  dimensions and coordinates to support metadata aware operations. The API is
 |  similar to that for the pandas Series or DataFrame, but DataArray objects
 |  can have any number of dimensions, and their contents have fixed data
 |  types.
 |  
 |  Additional features over raw numpy arrays:
 |  
 |  - Apply operations over dimensions by name: ``x.sum('time')``.
 |  - Select or assign values by integer location (like numpy): ``x[:10]``
 |    or by label (like pandas): ``x.loc['2014-01-01']`` or
 |    ``x.sel(time='2014-01-01')``.
 |  - Mathematical operations (e.g., ``x - y``) vectorize across multiple
 |    dimensions (known in numpy as "broadcasting") based on dimension names,
 |    regardless of thei

In [37]:
t=xr.DataArray(a)

In [38]:
t

<xarray.DataArray (dim_0: 50, dim_1: 50)>
array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])
Dimensions without coordinates: dim_0, dim_1

In [39]:
t.size

2500

In [40]:
t.shape

(50, 50)

In [41]:
t.values

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [42]:
t.name

In [44]:
t.rename('2DTest')

<xarray.DataArray '2DTest' (dim_0: 50, dim_1: 50)>
array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])
Dimensions without coordinates: dim_0, dim_1