In [2]:
import numpy as np

In [5]:
output_array = np.zeros((14,4,3), dtype=np.float32)
for i in range(14):
    mat = np.random.rand(4,3)
    output_array[i] = mat

In [6]:
output_array

array([[[0.612166  , 0.086602  , 0.04225902],
        [0.98209095, 0.06210275, 0.32023424],
        [0.05297995, 0.11876907, 0.4504795 ],
        [0.29388422, 0.73193616, 0.23345035]],

       [[0.23526764, 0.5153733 , 0.66849965],
        [0.74755454, 0.23864603, 0.58179474],
        [0.3558022 , 0.1194774 , 0.25879085],
        [0.500115  , 0.94838446, 0.2947674 ]],

       [[0.19810627, 0.11604852, 0.6968081 ],
        [0.10551651, 0.74905413, 0.16817139],
        [0.47279564, 0.7817949 , 0.17625932],
        [0.67614716, 0.9526403 , 0.09916047]],

       [[0.04577954, 0.44809738, 0.8409271 ],
        [0.38579747, 0.991371  , 0.7627571 ],
        [0.90611327, 0.6551155 , 0.18137285],
        [0.23176843, 0.43555325, 0.8267309 ]],

       [[0.3358047 , 0.69908565, 0.6745885 ],
        [0.19779533, 0.10082885, 0.08072492],
        [0.02084283, 0.7896415 , 0.7854796 ],
        [0.60806435, 0.16778533, 0.85163397]],

       [[0.39768586, 0.00428783, 0.47645104],
        [0.6218031 , 0.7

In [7]:
output_array.shape

(14, 4, 3)

In [8]:
output_array2 = np.zeros((14,4,3), dtype=np.float32)


In [9]:
output_array2

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0

In [11]:
output_array2.shape

(14, 4, 3)

In [12]:
output_array3 = np.zeros((14,4,3), dtype=np.float32)
for i in range(14):
    mat = np.random.rand(1,3)
    output_array3[i] = mat

In [14]:
output_array3.shape

(14, 4, 3)

In [16]:
mat.shape

(1, 3)

In [23]:
oa4 = np.zeros((14,14,3), dtype=np.float32)
for i in range(14):
    mat = np.random.rand(8,3)
    oa4[i] = mat

ValueError: could not broadcast input array from shape (8,3) into shape (14,3)

In [25]:
a = np.array((10,20,3))
b = np.array((1,3,4))
np.dstack((a,b))

array([[[10,  1],
        [20,  3],
        [ 3,  4]]])

In [26]:
a = np.array((2030,1354))
b = np.array((2030,1354))
np.dstack((a,b))

array([[[2030, 2030],
        [1354, 1354]]])