In [2]:
import pandas as pd

In [3]:
import xarray as xr

In [4]:
import numpy as np

In [5]:
a = np.array(np.random.randint(1, 90+1,(4,4)),dtype=np.float64)

In [6]:
b = np.array(np.random.randint(1, 360+1,(4,4)),dtype=np.float64)

In [7]:
c = np.random.random_sample(16,)
c = c.reshape(4,4)

In [8]:
dsa = xr.Dataset()

In [9]:
dsa

<xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*

In [10]:
dsa['CloudFraction'] = (('x', 'y'), c)

In [11]:
dsa.coords['latitude'] = (('x', 'y'), a)
dsa.coords['longitude'] = (('x', 'y'), b)

In [12]:
dsa

<xarray.Dataset>
Dimensions:        (x: 4, y: 4)
Coordinates:
    latitude       (x, y) float64 11.0 23.0 24.0 60.0 ... 65.0 69.0 12.0 86.0
    longitude      (x, y) float64 154.0 31.0 264.0 332.0 ... 214.0 178.0 200.0
Dimensions without coordinates: x, y
Data variables:
    CloudFraction  (x, y) float64 0.3104 0.6649 0.6682 ... 0.9633 0.6332 0.7996

In [13]:
dsa['latitude']

<xarray.DataArray 'latitude' (x: 4, y: 4)>
array([[11., 23., 24., 60.],
       [29., 86., 38., 47.],
       [85., 70., 10., 87.],
       [65., 69., 12., 86.]])
Coordinates:
    latitude   (x, y) float64 11.0 23.0 24.0 60.0 29.0 ... 65.0 69.0 12.0 86.0
    longitude  (x, y) float64 154.0 31.0 264.0 332.0 ... 21.0 214.0 178.0 200.0
Dimensions without coordinates: x, y

In [14]:
dsa['longitude']

<xarray.DataArray 'longitude' (x: 4, y: 4)>
array([[154.,  31., 264., 332.],
       [212.,  96., 131.,  81.],
       [131., 104., 315., 201.],
       [ 21., 214., 178., 200.]])
Coordinates:
    latitude   (x, y) float64 11.0 23.0 24.0 60.0 29.0 ... 65.0 69.0 12.0 86.0
    longitude  (x, y) float64 154.0 31.0 264.0 332.0 ... 21.0 214.0 178.0 200.0
Dimensions without coordinates: x, y

In [15]:
dsa['latitude'][0:2,0:2]

<xarray.DataArray 'latitude' (x: 2, y: 2)>
array([[11., 23.],
       [29., 86.]])
Coordinates:
    latitude   (x, y) float64 11.0 23.0 29.0 86.0
    longitude  (x, y) float64 154.0 31.0 212.0 96.0
Dimensions without coordinates: x, y

In [16]:
dsa['CloudFraction'][0:2,0:2]

<xarray.DataArray 'CloudFraction' (x: 2, y: 2)>
array([[0.310395, 0.664913],
       [0.965322, 0.789913]])
Coordinates:
    latitude   (x, y) float64 11.0 23.0 29.0 86.0
    longitude  (x, y) float64 154.0 31.0 212.0 96.0
Dimensions without coordinates: x, y

### Conditional Arguments For Parsing Data Through A Dataset

In [17]:
dsa.where(dsa.latitude > 40.0 , dsa.longitude < 60.0)

<xarray.Dataset>
Dimensions:        (x: 4, y: 4)
Coordinates:
    latitude       (x, y) float64 11.0 23.0 24.0 60.0 ... 65.0 69.0 12.0 86.0
    longitude      (x, y) float64 154.0 31.0 264.0 332.0 ... 214.0 178.0 200.0
Dimensions without coordinates: x, y
Data variables:
    CloudFraction  (x, y) float64 0.0 1.0 0.0 0.05973 ... 0.9633 0.0 0.7996

In [20]:
dsa['CloudFraction']

<xarray.DataArray 'CloudFraction' (x: 4, y: 4)>
array([[0.310395, 0.664913, 0.668172, 0.059725],
       [0.965322, 0.789913, 0.124717, 0.115879],
       [0.789728, 0.629522, 0.561155, 0.246527],
       [0.280067, 0.963333, 0.633236, 0.799648]])
Coordinates:
    latitude   (x, y) float64 11.0 23.0 24.0 60.0 29.0 ... 65.0 69.0 12.0 86.0
    longitude  (x, y) float64 154.0 31.0 264.0 332.0 ... 21.0 214.0 178.0 200.0
Dimensions without coordinates: x, y

In [18]:
dsa['CloudFraction'].where(dsa.latitude > 40.0 , dsa.longitude < 60.0)

<xarray.DataArray (x: 4, y: 4)>
array([[0.      , 1.      , 0.      , 0.059725],
       [0.      , 0.789913, 0.      , 0.115879],
       [0.789728, 0.629522, 0.      , 0.246527],
       [0.280067, 0.963333, 0.      , 0.799648]])
Coordinates:
    latitude   (x, y) float64 11.0 23.0 24.0 60.0 29.0 ... 65.0 69.0 12.0 86.0
    longitude  (x, y) float64 154.0 31.0 264.0 332.0 ... 21.0 214.0 178.0 200.0
Dimensions without coordinates: x, y

In [29]:
dsa['CloudFraction'].where(dsa.latitude < 80 , dsa.longitude > 95)

<xarray.DataArray (x: 4, y: 4)>
array([[0.310395, 0.664913, 0.668172, 0.059725],
       [0.965322, 1.      , 0.124717, 0.115879],
       [1.      , 0.629522, 0.561155, 1.      ],
       [0.280067, 0.963333, 0.633236, 1.      ]])
Coordinates:
    latitude   (x, y) float64 11.0 23.0 24.0 60.0 29.0 ... 65.0 69.0 12.0 86.0
    longitude  (x, y) float64 154.0 31.0 264.0 332.0 ... 21.0 214.0 178.0 200.0
Dimensions without coordinates: x, y

In [31]:
dsa['CloudFraction'].where(dsa.latitude == 86 , dsa.longitude == 96)

<xarray.DataArray (x: 4, y: 4)>
array([[0.      , 0.      , 0.      , 0.      ],
       [0.      , 0.789913, 0.      , 0.      ],
       [0.      , 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , 0.799648]])
Coordinates:
    latitude   (x, y) float64 11.0 23.0 24.0 60.0 29.0 ... 65.0 69.0 12.0 86.0
    longitude  (x, y) float64 154.0 31.0 264.0 332.0 ... 21.0 214.0 178.0 200.0
Dimensions without coordinates: x, y

In [45]:
dsa['CloudFraction'].where(dsa.latitude == 86 , dsa.longitude == 96)

<xarray.DataArray (x: 4, y: 4)>
array([[0.      , 0.      , 0.      , 0.      ],
       [0.      , 0.789913, 0.      , 0.      ],
       [0.      , 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , 0.799648]])
Coordinates:
    latitude   (x, y) float64 11.0 23.0 24.0 60.0 29.0 ... 65.0 69.0 12.0 86.0
    longitude  (x, y) float64 154.0 31.0 264.0 332.0 ... 21.0 214.0 178.0 200.0
Dimensions without coordinates: x, y

In [42]:
s = dsa['CloudFraction'].where(dsa.latitude == 86 , dsa.longitude == 96)

In [44]:
s.data

array([[0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.7899133 , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.79964842]])

In [47]:
s.item

<bound method _values_method_wrapper.<locals>.func of <xarray.DataArray (x: 4, y: 4)>
array([[0.      , 0.      , 0.      , 0.      ],
       [0.      , 0.789913, 0.      , 0.      ],
       [0.      , 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , 0.799648]])
Coordinates:
    latitude   (x, y) float64 11.0 23.0 24.0 60.0 29.0 ... 65.0 69.0 12.0 86.0
    longitude  (x, y) float64 154.0 31.0 264.0 332.0 ... 21.0 214.0 178.0 200.0
Dimensions without coordinates: x, y>

In [48]:
s

<xarray.DataArray (x: 4, y: 4)>
array([[0.      , 0.      , 0.      , 0.      ],
       [0.      , 0.789913, 0.      , 0.      ],
       [0.      , 0.      , 0.      , 0.      ],
       [0.      , 0.      , 0.      , 0.799648]])
Coordinates:
    latitude   (x, y) float64 11.0 23.0 24.0 60.0 29.0 ... 65.0 69.0 12.0 86.0
    longitude  (x, y) float64 154.0 31.0 264.0 332.0 ... 21.0 214.0 178.0 200.0
Dimensions without coordinates: x, y

In [49]:
ssem = s.to_series()

In [50]:
ssem

x  y
0  0    0.000000
   1    0.000000
   2    0.000000
   3    0.000000
1  0    0.000000
   1    0.789913
   2    0.000000
   3    0.000000
2  0    0.000000
   1    0.000000
   2    0.000000
   3    0.000000
3  0    0.000000
   1    0.000000
   2    0.000000
   3    0.799648
dtype: float64

In [53]:
dsa['CloudFraction'].where(dsa.latitude < 20.0 , dsa.latitude > 21.0)

<xarray.DataArray (x: 4, y: 4)>
array([[0.310395, 1.      , 1.      , 1.      ],
       [1.      , 1.      , 1.      , 1.      ],
       [1.      , 1.      , 0.561155, 1.      ],
       [1.      , 1.      , 0.633236, 1.      ]])
Coordinates:
    latitude   (x, y) float64 11.0 23.0 24.0 60.0 29.0 ... 65.0 69.0 12.0 86.0
    longitude  (x, y) float64 154.0 31.0 264.0 332.0 ... 21.0 214.0 178.0 200.0
Dimensions without coordinates: x, y

In [54]:
dsa['CloudFraction'].where(dsa.latitude < 20.0 , dsa.latitude > 21.0, dsa.longitude < 131.0 , dsa.longitude > 132.0)

TypeError: where() takes from 2 to 4 positional arguments but 5 were given

In [57]:
z = dsa['CloudFraction'].where(dsa.latitude < 20.0 , dsa.latitude > 21.0)

In [58]:
z

<xarray.DataArray (x: 4, y: 4)>
array([[0.310395, 1.      , 1.      , 1.      ],
       [1.      , 1.      , 1.      , 1.      ],
       [1.      , 1.      , 0.561155, 1.      ],
       [1.      , 1.      , 0.633236, 1.      ]])
Coordinates:
    latitude   (x, y) float64 11.0 23.0 24.0 60.0 29.0 ... 65.0 69.0 12.0 86.0
    longitude  (x, y) float64 154.0 31.0 264.0 332.0 ... 21.0 214.0 178.0 200.0
Dimensions without coordinates: x, y

In [60]:
z.where(dsa.longitude < 155.0 , dsa.longitude > 153.0)

<xarray.DataArray (x: 4, y: 4)>
array([[0.310395, 1.      , 1.      , 1.      ],
       [1.      , 1.      , 1.      , 1.      ],
       [1.      , 1.      , 1.      , 1.      ],
       [1.      , 1.      , 1.      , 1.      ]])
Coordinates:
    latitude   (x, y) float64 11.0 23.0 24.0 60.0 29.0 ... 65.0 69.0 12.0 86.0
    longitude  (x, y) float64 154.0 31.0 264.0 332.0 ... 21.0 214.0 178.0 200.0
Dimensions without coordinates: x, y

In [61]:
dab = xr.DataArray([[92,10],[91,9],[90,10],[89,11],
                    [59,1],[92,8],[93,7],[93,3],
                    [54,2],[94,6],[91,9],[92,2],
                    [25,3],[67,1],[92,10],[91,9]],
                  coords={'geo': (['lat','lon'], [[52,343],[11,339],[86,351],[52,108],[11,121],[51,245],
                                                 [84,165],[84,110],[32,318],[1,324],[11,357],[79,290],
                                                 [85,221],[60,78],[83,172],[68,225]])},
                  dims=['lat','lon'])

In [65]:
p = np.array([[92,10],[91,9],[90,10],[89,11],
 [59,1],[92,8],[93,7],[93,3],
 [54,2],[94,6],[91,9],[92,2],
 [25,3],[67,1],[92,10],[91,9]])

In [66]:
p

array([[92, 10],
       [91,  9],
       [90, 10],
       [89, 11],
       [59,  1],
       [92,  8],
       [93,  7],
       [93,  3],
       [54,  2],
       [94,  6],
       [91,  9],
       [92,  2],
       [25,  3],
       [67,  1],
       [92, 10],
       [91,  9]])

In [68]:
p1= np.array([{92,10},{91,9},{90,10},{89,11},
 {59,1},{92,8},{93,7},{93,3},
 {54,2},{94,6},{91,9},{92,2},
 {25,3},{67,1},{92,10},{91,9}])

In [69]:
p1

array([{10, 92}, {9, 91}, {90, 10}, {89, 11}, {1, 59}, {8, 92}, {93, 7},
       {3, 93}, {2, 54}, {94, 6}, {9, 91}, {2, 92}, {25, 3}, {1, 67},
       {10, 92}, {9, 91}], dtype=object)

In [70]:
p1.shape

(16,)

In [71]:
p2 = p1.reshape(4,4)

In [74]:
p2

array([[{10, 92}, {9, 91}, {90, 10}, {89, 11}],
       [{1, 59}, {8, 92}, {93, 7}, {3, 93}],
       [{2, 54}, {94, 6}, {9, 91}, {2, 92}],
       [{25, 3}, {1, 67}, {10, 92}, {9, 91}]], dtype=object)

In [76]:
dab = xr.DataArray(p2,
                   coords={'geo': (['lat','lon'], p2)},
                  dims=['lat','lon'])

In [77]:
dab

<xarray.DataArray (lat: 4, lon: 4)>
array([[{10, 92}, {9, 91}, {90, 10}, {89, 11}],
       [{1, 59}, {8, 92}, {93, 7}, {3, 93}],
       [{2, 54}, {94, 6}, {9, 91}, {2, 92}],
       [{25, 3}, {1, 67}, {10, 92}, {9, 91}]], dtype=object)
Coordinates:
    geo      (lat, lon) object {10, 92} {9, 91} {90, 10} ... {10, 92} {9, 91}
Dimensions without coordinates: lat, lon

In [82]:
#Condtional Arguments Apply Through Dimensions Indexs 
dab.where(dab['geo']['lat'] < 2.0)

<xarray.DataArray (lat: 4, lon: 4)>
array([[{10, 92}, {9, 91}, {90, 10}, {89, 11}],
       [{1, 59}, {8, 92}, {93, 7}, {3, 93}],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]], dtype=object)
Coordinates:
    geo      (lat, lon) object {10, 92} {9, 91} {90, 10} ... {10, 92} {9, 91}
Dimensions without coordinates: lat, lon

In [87]:
dab.where(dab['geo']['lat'] < 1.0, dab['geo']['lon'] < 31.0)

<xarray.DataArray (lat: 4, lon: 4)>
array([[{10, 92}, {9, 91}, {90, 10}, {89, 11}],
       [True, True, True, True],
       [True, True, True, True],
       [True, True, True, True]], dtype=object)
Coordinates:
    geo      (lat, lon) object {10, 92} {9, 91} {90, 10} ... {10, 92} {9, 91}
Dimensions without coordinates: lat, lon

In [90]:
dab.where(dab['geo']['lat'] == 10.0)

<xarray.DataArray (lat: 4, lon: 4)>
array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]], dtype=object)
Coordinates:
    geo      (lat, lon) object {10, 92} {9, 91} {90, 10} ... {10, 92} {9, 91}
Dimensions without coordinates: lat, lon

In [91]:
dab['geo']

<xarray.DataArray 'geo' (lat: 4, lon: 4)>
array([[{10, 92}, {9, 91}, {90, 10}, {89, 11}],
       [{1, 59}, {8, 92}, {93, 7}, {3, 93}],
       [{2, 54}, {94, 6}, {9, 91}, {2, 92}],
       [{25, 3}, {1, 67}, {10, 92}, {9, 91}]], dtype=object)
Coordinates:
    geo      (lat, lon) object {10, 92} {9, 91} {90, 10} ... {10, 92} {9, 91}
Dimensions without coordinates: lat, lon

In [92]:
dab['geo']['lat']

<xarray.DataArray 'lat' (lat: 4)>
array([0, 1, 2, 3])
Dimensions without coordinates: lat

In [93]:
p3= np.array([{52,343},{11,339},{86,351},{52,108},
 {11,121},{51,245},{84,165},{84,110},
 {32,318},{1,324},{11,357},{79,290},
 {85,221},{60,78},{83,172},{68,225}])

In [94]:
p4 = p3.reshape(4,4)

In [95]:
p4

array([[{52, 343}, {339, 11}, {86, 351}, {108, 52}],
       [{121, 11}, {51, 245}, {84, 165}, {84, 110}],
       [{32, 318}, {1, 324}, {11, 357}, {290, 79}],
       [{221, 85}, {60, 78}, {83, 172}, {225, 68}]], dtype=object)

In [97]:
dab1 = xr.DataArray(p2,
                   coords={'geo': (['lat','lon'], p4)},
                  dims=['lat','lon'])

In [98]:
dab1

<xarray.DataArray (lat: 4, lon: 4)>
array([[{10, 92}, {9, 91}, {90, 10}, {89, 11}],
       [{1, 59}, {8, 92}, {93, 7}, {3, 93}],
       [{2, 54}, {94, 6}, {9, 91}, {2, 92}],
       [{25, 3}, {1, 67}, {10, 92}, {9, 91}]], dtype=object)
Coordinates:
    geo      (lat, lon) object {52, 343} {339, 11} ... {83, 172} {225, 68}
Dimensions without coordinates: lat, lon

In [99]:
dab1.where(dab['geo']['lat'] < 2.0)

<xarray.DataArray (lat: 4, lon: 4)>
array([[{10, 92}, {9, 91}, {90, 10}, {89, 11}],
       [{1, 59}, {8, 92}, {93, 7}, {3, 93}],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]], dtype=object)
Coordinates:
    geo      (lat, lon) object {52, 343} {339, 11} ... {83, 172} {225, 68}
Dimensions without coordinates: lat, lon

In [100]:
dab1.where(dab['geo']['lat'] == 2.0)

<xarray.DataArray (lat: 4, lon: 4)>
array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [{2, 54}, {94, 6}, {9, 91}, {2, 92}],
       [nan, nan, nan, nan]], dtype=object)
Coordinates:
    geo      (lat, lon) object {52, 343} {339, 11} ... {83, 172} {225, 68}
Dimensions without coordinates: lat, lon

In [101]:
dab1.where(dab['geo']['lat'] == 2.0, dab['geo']['lon'] == 1.0)

<xarray.DataArray (lat: 4, lon: 4)>
array([[False, True, False, False],
       [False, True, False, False],
       [{2, 54}, {94, 6}, {9, 91}, {2, 92}],
       [False, True, False, False]], dtype=object)
Coordinates:
    geo      (lat, lon) object {52, 343} {339, 11} ... {83, 172} {225, 68}
Dimensions without coordinates: lat, lon

In [104]:
dab1.where(dab['geo']['lat'] == 2.0 && dab['geo']['lon'] == 1.0)

SyntaxError: invalid syntax (<ipython-input-104-3a525ff9159b>, line 1)

In [105]:
dab1.where(dab['geo']['lat'] == 2.0 and dab['geo']['lon'] == 1.0)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [106]:
dab1.where(dab['geo']['lat'] == 2.0 + dab['geo']['lon'] == 1.0)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [107]:
dab1.where(dab['geo']['lat'] == 2.0 or dab['geo']['lon'] == 1.0)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [108]:
dab1.where(dab['geo']['lat'] == 2.0 || dab['geo']['lon'] == 1.0)

SyntaxError: invalid syntax (<ipython-input-108-f5c6657f5168>, line 1)

In [9]:
np.version.version

'1.15.1'

In [11]:
xr.version.version

AttributeError: module 'xarray' has no attribute 'version'