In [76]:
import xarray as xr

In [77]:
import numpy as np
import pandas as pd

In [78]:
data = np.random.rand(4, 3)

In [79]:
data

array([[0.11990968, 0.25577627, 0.32182621],
       [0.46037031, 0.1919962 , 0.77834427],
       [0.52742431, 0.60210087, 0.08578772],
       [0.54834843, 0.54209153, 0.03098254]])

In [80]:
locs = ['IA', 'IL', 'IN']
locs

['IA', 'IL', 'IN']

In [81]:
times = pd.date_range('2000-01-01', periods=4)
times

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04'], dtype='datetime64[ns]', freq='D')

In [82]:
foo = xr.DataArray(data, coords=[times, locs], dims=['time', 'space'])
foo

<xarray.DataArray (time: 4, space: 3)>
array([[0.11991 , 0.255776, 0.321826],
       [0.46037 , 0.191996, 0.778344],
       [0.527424, 0.602101, 0.085788],
       [0.548348, 0.542092, 0.030983]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space    (space) <U2 'IA' 'IL' 'IN'

In [108]:
foo.dims

('time', 'space')

In [109]:
foo.coords

Coordinates:
  * time      (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space     (space) <U2 'IA' 'IL' 'IN'
    ranking2  (space) int64 1 2 3
    ranking3  (time) int64 1 2 3 4

In [113]:
foo?

In [83]:
foo1 = xr.DataArray(data)
foo1

<xarray.DataArray (dim_0: 4, dim_1: 3)>
array([[0.11991 , 0.255776, 0.321826],
       [0.46037 , 0.191996, 0.778344],
       [0.527424, 0.602101, 0.085788],
       [0.548348, 0.542092, 0.030983]])
Dimensions without coordinates: dim_0, dim_1

In [84]:
foo1.values

array([[0.11990968, 0.25577627, 0.32182621],
       [0.46037031, 0.1919962 , 0.77834427],
       [0.52742431, 0.60210087, 0.08578772],
       [0.54834843, 0.54209153, 0.03098254]])

In [85]:
foo1.dims

('dim_0', 'dim_1')

In [86]:
foo1.coords

Coordinates:
    *empty*

In [87]:
foo.attrs

OrderedDict()

In [88]:
print(foo1.name)

None


In [89]:
foo1.values = 10 * foo.values

In [90]:
foo1.values

array([[1.19909681, 2.55776274, 3.21826213],
       [4.60370313, 1.91996204, 7.78344269],
       [5.27424308, 6.02100871, 0.8578772 ],
       [5.48348434, 5.42091529, 0.30982542]])

In [91]:
##Now fill in some of that missing metadata:

In [92]:
foo1.name = 'foo1'
print(foo1.name)

foo1


In [93]:
foo1.attrs['units'] = 'meters'

In [94]:
foo1

<xarray.DataArray 'foo1' (dim_0: 4, dim_1: 3)>
array([[1.199097, 2.557763, 3.218262],
       [4.603703, 1.919962, 7.783443],
       [5.274243, 6.021009, 0.857877],
       [5.483484, 5.420915, 0.309825]])
Dimensions without coordinates: dim_0, dim_1
Attributes:
    units:    meters

In [95]:
foo1.rename('bar')

<xarray.DataArray 'bar' (dim_0: 4, dim_1: 3)>
array([[1.199097, 2.557763, 3.218262],
       [4.603703, 1.919962, 7.783443],
       [5.274243, 6.021009, 0.857877],
       [5.483484, 5.420915, 0.309825]])
Dimensions without coordinates: dim_0, dim_1
Attributes:
    units:    meters

DataArray Coordinates

The coords property is dict like.
Individual coordinates can be accessed from the coordinates by name, or even by indexing the data array itself:

In [96]:
foo.coords['time']

<xarray.DataArray 'time' (time: 4)>
array(['2000-01-01T00:00:00.000000000', '2000-01-02T00:00:00.000000000',
       '2000-01-03T00:00:00.000000000', '2000-01-04T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04

In [97]:
foo['time']

<xarray.DataArray 'time' (time: 4)>
array(['2000-01-01T00:00:00.000000000', '2000-01-02T00:00:00.000000000',
       '2000-01-03T00:00:00.000000000', '2000-01-04T00:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04

These are also DataArray objects, which contain tick-labels for each dimension.

Coordinates can also be set or removed by using the dictionary like syntax:

In [106]:
foo['ranking3'] = ('time', [1, 2, 3,4])

In [117]:
foo.dims

('time', 'space')

In [107]:
foo.coords

Coordinates:
  * time      (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
  * space     (space) <U2 'IA' 'IL' 'IN'
    ranking2  (space) int64 1 2 3
    ranking3  (time) int64 1 2 3 4

In [123]:
del foo['space']

In [124]:
foo.coords

Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04

In [125]:
foo.dims

('time', 'space')

Dataset

xarray.Dataset is xarray’s multi-dimensional equivalent of a DataFrame.

In [126]:
foo

<xarray.DataArray (time: 4, space: 3)>
array([[0.11991 , 0.255776, 0.321826],
       [0.46037 , 0.191996, 0.778344],
       [0.527424, 0.602101, 0.085788],
       [0.548348, 0.542092, 0.030983]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
Dimensions without coordinates: space

In [127]:
temp = 15 + 8 * np.random.randn(2, 2, 3)
temp

array([[[19.59590546, 12.51220676, 21.19979916],
        [21.1654601 , 20.8970516 , -0.82777549]],

       [[13.65197635, 13.35129969,  3.86078281],
        [27.64133861, 24.77035439, 20.37248759]]])

In [128]:
precip = 10 * np.random.rand(2, 2, 3)
precip

array([[[5.73628685, 2.67718171, 5.79587617],
        [8.17883641, 1.15584762, 3.89401725]],

       [[3.17373665, 4.87344408, 6.75295838],
        [0.04465761, 8.58137194, 7.2825498 ]]])

In [129]:
lon = [[-99.83, -99.32], [-99.79, -99.23]]
lon

[[-99.83, -99.32], [-99.79, -99.23]]

In [130]:
lat = [[42.25, 42.21], [42.63, 42.59]]
lat

[[42.25, 42.21], [42.63, 42.59]]

In [131]:
 ds = xr.Dataset({'temperature': (['x', 'y', 'time'],  temp),
                  'precipitation': (['x', 'y', 'time'], precip)},
                  coords={'lon': (['x', 'y'], lon),
                        'lat': (['x', 'y'], lat),
                        'time': pd.date_range('2014-09-06', periods=3),
                        'reference_time': pd.Timestamp('2014-09-05')})

In [142]:
ds.data_vars['bar'] = foo

TypeError: 'DataVariables' object does not support item assignment

In [ ]:
figur out to add data variaboe to a dataset

In [133]:
xr.Dataset({'bar': foo})

<xarray.Dataset>
Dimensions:  (space: 3, time: 4)
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-02 2000-01-03 2000-01-04
Dimensions without coordinates: space
Data variables:
    bar      (time, space) float64 0.1199 0.2558 0.3218 ... 0.5421 0.03098

Dataset Contents

In [141]:
'temperature' in ds

True

In [139]:
ds['temperature']

<xarray.DataArray 'temperature' (x: 2, y: 2, time: 3)>
array([[[19.595905, 12.512207, 21.199799],
        [21.16546 , 20.897052, -0.827775]],

       [[13.651976, 13.3513  ,  3.860783],
        [27.641339, 24.770354, 20.372488]]])
Coordinates:
    lon             (x, y) float64 -99.83 -99.32 -99.79 -99.23
    lat             (x, y) float64 42.25 42.21 42.63 42.59
  * time            (time) datetime64[ns] 2014-09-06 2014-09-07 2014-09-08
    reference_time  datetime64[ns] 2014-09-05
Dimensions without coordinates: x, y

In [60]:
ds.data_vars

Data variables:
    temperature    (x, y, time) float64 25.98 8.534 14.42 ... 25.52 22.07 16.43
    precipitation  (x, y, time) float64 0.2005 1.032 7.911 ... 1.797 4.051 6.401

In [61]:
ds.coords

Coordinates:
    lon             (x, y) float64 -99.83 -99.32 -99.79 -99.23
    lat             (x, y) float64 42.25 42.21 42.63 42.59
  * time            (time) datetime64[ns] 2014-09-06 2014-09-07 2014-09-08
    reference_time  datetime64[ns] 2014-09-05

Like data arrays, datasets also store arbitrary metadata in the form of attributes:

In [62]:
ds.attrs

OrderedDict()

In [63]:
ds.attrs['title'] = 'Test attribute'

In [64]:
ds

<xarray.Dataset>
Dimensions:         (time: 3, x: 2, y: 2)
Coordinates:
    lon             (x, y) float64 -99.83 -99.32 -99.79 -99.23
    lat             (x, y) float64 42.25 42.21 42.63 42.59
  * time            (time) datetime64[ns] 2014-09-06 2014-09-07 2014-09-08
    reference_time  datetime64[ns] 2014-09-05
Dimensions without coordinates: x, y
Data variables:
    temperature     (x, y, time) float64 25.98 8.534 14.42 ... 25.52 22.07 16.43
    precipitation   (x, y, time) float64 0.2005 1.032 7.911 ... 4.051 6.401
Attributes:
    title:    Test attribute

---------------------

As a useful shortcut, you can use attribute style access for reading (but not setting) variables and attributes:

In [65]:
ds.temperature

<xarray.DataArray 'temperature' (x: 2, y: 2, time: 3)>
array([[[25.981561,  8.533999, 14.42064 ],
        [11.575883,  3.638272,  8.862933]],

       [[ 9.709541, 22.699351, 17.975598],
        [25.515913, 22.066712, 16.43442 ]]])
Coordinates:
    lon             (x, y) float64 -99.83 -99.32 -99.79 -99.23
    lat             (x, y) float64 42.25 42.21 42.63 42.59
  * time            (time) datetime64[ns] 2014-09-06 2014-09-07 2014-09-08
    reference_time  datetime64[ns] 2014-09-05
Dimensions without coordinates: x, y

This is particularly useful in an exploratory context, because you can tab-complete these variable names with tools like IPython.

If a dimension name is given as an argument to drop, it also drops all variables that use that dimension: