# Interpolating Data

xarray offers flexible interpolation routines, which have a similar interface to our indexing.

In [2]:
import xarray as xr
import pandas as pd
import numpy as np

In [3]:
da = xr.DataArray(np.sin(0.3 * np.arange(12).reshape(4, 3)),
                     [('time', np.arange(4)),
                     ('space', [0.1, 0.2, 0.3])])

In [4]:
da

<xarray.DataArray (time: 4, space: 3)>
array([[ 0.      ,  0.29552 ,  0.564642],
       [ 0.783327,  0.932039,  0.997495],
       [ 0.973848,  0.863209,  0.675463],
       [ 0.42738 ,  0.14112 , -0.157746]])
Coordinates:
  * time     (time) int64 0 1 2 3
  * space    (space) float64 0.1 0.2 0.3

In [6]:
da.sel(time=3)

<xarray.DataArray (space: 3)>
array([ 0.42738 ,  0.14112 , -0.157746])
Coordinates:
    time     int64 3
  * space    (space) float64 0.1 0.2 0.3

In [7]:
da.interp(time=[2.5])

<xarray.DataArray (time: 1, space: 3)>
array([[0.700614, 0.502165, 0.258859]])
Coordinates:
  * space    (space) float64 0.1 0.2 0.3
  * time     (time) float64 2.5

In [8]:
da

<xarray.DataArray (time: 4, space: 3)>
array([[ 0.      ,  0.29552 ,  0.564642],
       [ 0.783327,  0.932039,  0.997495],
       [ 0.973848,  0.863209,  0.675463],
       [ 0.42738 ,  0.14112 , -0.157746]])
Coordinates:
  * time     (time) int64 0 1 2 3
  * space    (space) float64 0.1 0.2 0.3

In [10]:
da.interp(time = [2.5,3.5])

<xarray.DataArray (time: 2, space: 3)>
array([[0.700614, 0.502165, 0.258859],
       [     nan,      nan,      nan]])
Coordinates:
  * space    (space) float64 0.1 0.2 0.3
  * time     (time) float64 2.5 3.5

In [11]:
da.interp(time=[2,3])

<xarray.DataArray (time: 2, space: 3)>
array([[ 0.973848,  0.863209,  0.675463],
       [ 0.42738 ,  0.14112 , -0.157746]])
Coordinates:
  * space    (space) float64 0.1 0.2 0.3
  * time     (time) int64 2 3

In [12]:
da

<xarray.DataArray (time: 4, space: 3)>
array([[ 0.      ,  0.29552 ,  0.564642],
       [ 0.783327,  0.932039,  0.997495],
       [ 0.973848,  0.863209,  0.675463],
       [ 0.42738 ,  0.14112 , -0.157746]])
Coordinates:
  * time     (time) int64 0 1 2 3
  * space    (space) float64 0.1 0.2 0.3

In [13]:
da.interp(space=[2,3])

<xarray.DataArray (time: 4, space: 2)>
array([[nan, nan],
       [nan, nan],
       [nan, nan],
       [nan, nan]])
Coordinates:
  * time     (time) int64 0 1 2 3
  * space    (space) int64 2 3

In [14]:
da_dt64 = xr.DataArray([1, 3],[('time', pd.date_range('1/1/2000', '1/3/2000', periods=2))])

In [15]:
da_dt64

<xarray.DataArray (time: 2)>
array([1, 3])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01 2000-01-03

In [27]:
da_dt64.interp(time='2000-03-01')

<xarray.DataArray ()>
array(nan)
Coordinates:
    time     datetime64[ns] 2000-03-01