In [1]:
import pandas as pd

In [2]:
import xarray as xr

In [3]:
import numpy as np

In [4]:
a = np.array(np.random.randint(1, 90+1,(4,4)),dtype=np.float64)

In [5]:
a

array([[65.,  9., 10., 21.],
       [85., 30., 44., 79.],
       [69., 44., 25., 70.],
       [ 3., 51., 22., 38.]])

In [6]:
a.shape

(4, 4)

In [7]:
c = np.random.random_sample(16,)

In [8]:
c.reshape(4,4)

array([[0.25635274, 0.00320031, 0.28313572, 0.32498661],
       [0.76855115, 0.50468301, 0.15229393, 0.69480762],
       [0.25767586, 0.58860906, 0.1651636 , 0.26380383],
       [0.17182203, 0.06115924, 0.76509114, 0.95798399]])

In [9]:
b = np.array(np.random.randint(1, 360+1,(4,4)),dtype=np.float64)

In [10]:
b

array([[308., 196., 210.,  73.],
       [108., 222., 332.,  66.],
       [238., 331., 323., 305.],
       [203., 258.,  67.,  71.]])

In [11]:
a

array([[65.,  9., 10., 21.],
       [85., 30., 44., 79.],
       [69., 44., 25., 70.],
       [ 3., 51., 22., 38.]])

In [12]:
b

array([[308., 196., 210.,  73.],
       [108., 222., 332.,  66.],
       [238., 331., 323., 305.],
       [203., 258.,  67.,  71.]])

In [13]:
c

array([0.25635274, 0.00320031, 0.28313572, 0.32498661, 0.76855115,
       0.50468301, 0.15229393, 0.69480762, 0.25767586, 0.58860906,
       0.1651636 , 0.26380383, 0.17182203, 0.06115924, 0.76509114,
       0.95798399])

In [14]:
c = c.reshape(4,4)

In [15]:
c

array([[0.25635274, 0.00320031, 0.28313572, 0.32498661],
       [0.76855115, 0.50468301, 0.15229393, 0.69480762],
       [0.25767586, 0.58860906, 0.1651636 , 0.26380383],
       [0.17182203, 0.06115924, 0.76509114, 0.95798399]])

In [16]:
dsa = xr.Dataset()

In [17]:
dsa

<xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*

In [18]:
dsa['CloudFraction'] = (('x', 'y'), c)

In [19]:
dsa

<xarray.Dataset>
Dimensions:        (x: 4, y: 4)
Dimensions without coordinates: x, y
Data variables:
    CloudFraction  (x, y) float64 0.2564 0.0032 0.2831 ... 0.06116 0.7651 0.958

In [21]:
dsa.coords['latitude'] = (('x', 'y'), a)

In [22]:
dsa.coords['longitude'] = (('x', 'y'), b)

In [23]:
dsa
#StackOverflow.

<xarray.Dataset>
Dimensions:        (x: 4, y: 4)
Coordinates:
    latitude       (x, y) float64 23.0 16.0 53.0 1.0 ... 82.0 65.0 45.0 88.0
    longitude      (x, y) float64 219.0 13.0 276.0 69.0 ... 156.0 277.0 16.0
Dimensions without coordinates: x, y
Data variables:
    CloudFraction  (x, y) float64 0.1599 0.05671 0.8624 ... 0.7757 0.7572

In [24]:
dsa['CloudFraction'][0][0]

<xarray.DataArray 'CloudFraction' ()>
array(0.159909)
Coordinates:
    latitude   float64 23.0
    longitude  float64 219.0

In [25]:
dsa

<xarray.Dataset>
Dimensions:        (x: 4, y: 4)
Coordinates:
    latitude       (x, y) float64 23.0 16.0 53.0 1.0 ... 82.0 65.0 45.0 88.0
    longitude      (x, y) float64 219.0 13.0 276.0 69.0 ... 156.0 277.0 16.0
Dimensions without coordinates: x, y
Data variables:
    CloudFraction  (x, y) float64 0.1599 0.05671 0.8624 ... 0.7757 0.7572

In [26]:
dsa['y']

<xarray.DataArray 'y' (y: 4)>
array([0, 1, 2, 3])
Dimensions without coordinates: y

In [27]:
ds['lat'][0]

NameError: name 'ds' is not defined

In [ ]:
dsa['CloudFraction'][1][1]

In [ ]:
dsa.sel(x=[0],y=[0])

In [ ]:
dsa['CloudFraction'][0][0]

In [ ]:
# To find the output of this -> dsa['latitude'][0][0]
dsa.where(dsa.latitude == 31.0)

In [ ]:
dsa.where(dsa.latitude < 31.0, dsa.longitude > 127.0)

In [ ]:
dsa

In [ ]:
dsa['latitude'][:]

In [ ]:
dsa

In [ ]:
dsa['latitude'][1][0]

In [ ]:
dsa

In [ ]:
dsa

In [ ]:
dsa['latitude']

In [ ]:
x_range = [30,50,70,90]

In [ ]:
x_labels = ['low','mid','high']

In [ ]:
dsa.groupby_bins('latitude', [30,50,70,90])

In [ ]:
dsa.groupby_bins('latitude', [30,50,70,90]).groups

In [ ]:
intervals = pd.Series(dsa.groupby_bins('latitude', [30,50,70,90]).groups)

In [ ]:
intervals

In [ ]:
dsa.where(dsa.latitude == 31.0)

In [ ]:
dsa['latitude'][0]

In [ ]:
dsa.groupby_bins('x', [30,50,70,90]).groups