In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [7]:
arr[:11]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
s = arr[1:]

In [13]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [14]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [15]:
arr_2d[2][2]

45

In [20]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])